### ISSUE TITLE
[Bug/auth-service] Company Search API 가 동작 되지 않음

### ISSUE THREAD

**Issue by DISNOTACAT** [Sparta-mosaic/msa-mosaic#24]
# 🐞 어떤 버그인가요?

페이징 요청시 500 에러 발생

## 📝 어떤 상황에서 발생한 버그인가요?

요청 url : http://localhost:19092/api/v1/company

## 🎯 예상 결과

{"success":true,"response":{"companyPage":{"content":[{"id":null,"name":"동백카츠 경북 도청점","address":"경북 예천군 호명면 새움1로 10","companyType":"DEMAND","userId":36,"hubId":16},{"id":null,"name":"파리바게뜨 옥암대우점","address":"전남 목포시 남악1로52번길 6-3 (옥암동) 1층(옥암동)","companyType":"DEMAND","userId":35,"hubId":15},{"id":null,"name":"롯데마트 전주점","address":"전북 전주시 완산구 우전로 240 롯데마트 전주점","companyType":"DEMAND","userId":34,"hubId":14},{"id":null,"name":"용봉보건진료소","address":"충남 홍성군 홍북읍 용봉산3길 136","companyType":"DEMAND","userId":33,"hubId":13},{"id":null,"name":"CGV 청주서문","address":"충북 청주시 상당구 상당로81번길 63","companyType":"DEMAND","userId":32,"hubId":12},{"id":null,"name":"레고랜드 코리아 리조트","address":"강원 춘천시 하중도길 128 레고랜드 코리아 리조트","companyType":"DEMAND","userId":31,"hubId":11},{"id":null,"name":"물빛광장문화공원","address":"세종 소담동 510-1","companyType":"DEMAND","userId":30,"hubId":10},{"id":null,"name":"옥동초등학교","address":"울산 남구 문수로 401","companyType":"DEMAND","userId":29,"hubId":9},{"id":null,"name":"스타벅스 대전대덕로점","address":"대전 서구 대덕대로234번길 18 (둔산동)","companyType":"DEMAND","userId":28,"hubId":8},{"id":null,"name":"상무조각공원","address":"광주 서구 상무시민로 3 세계광엑스포주제관","companyType":"DEMAND","userId":27,"hubId":7}],"page":{"size":10,"number":0,"totalElements":19,"totalPages":2}}}}

**Comment by lowgiant** [comment]
현재 user, company 스키마랑 data 제대로 안들어 가지고 있어요. 
ㄴ 이 부분 먼저 확인해보면 좋을 듯 싶어요. 

위 내용을 보면 id가 대부분 null이네요. ㅠㅠ

**Comment by DISNOTACAT** [comment]
페이징 버그는 해결했는데, 스키마는 다시 확인해보겠습니다ㅠㅠ

**Comment by lowgiant** [comment]
다행이네요 ㅠㅠ
yml 설정은 

spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql


이런식으로 구성하시면 되는데, 엔티티와 스키마 구조가 일치 하게끔 확인하면 됩니다.
